### ISSUE TITLE
Skip not accepted as last token in alternative of hexstring

### ISSUE THREAD

**Issue by aschuster99** [VirusTotal/yara#481] opened 2016-07-26 09:29 UTC
YARA complains about a hexstring if the last token in an alternative is a skip instruction. The following rule illustrates the problem:

rule hexstring_issue
{
  strings:
    // we search for a (fictious) sequence of x86 machine instructions
    $ok1 = { c3 (ff dd 8b | e8 [4] 8b) c3 }
    // now we factor out "8b"
    $fail = { c3 (ff dd | e8 [4]) 8b c3 }
    // wildcards instead of a skip are ok, though
    $ok2 = { c3 (ff dd | e8 ?? ?? ?? ??) 8b c3 }
  condition:
    any of them
}

Hexstring $fail causes YARA to fail, apparently because of the skip being the last token. Appending another byte works around the problem. So does replacing the skip with wildcards.

On a related note, YARA warns about $ok1 slowing down scanning, but $ok2 is fine.

**Comment by hillu** [comment] 2016-07-26 10:02
The error message with current master is

    invalid hex string "$fail": syntax error, unexpected ')', expecting _BYTE_ or _MASKED_BYTE_ or '(' or '['

YARA 3.4.0 does not have this problem. A quick `git bisect` run shows that this seems to be a regression inadvertently introduced with 30fbe81458512c83912131254f5012140c565c6d ("Reject hex strings starting or ending with jumps.").

**Comment by plusvic** [comment] 2016-08-09 19:18
Accepting ranges at the beginning/end of alternatives introduce a number of edge cases that is difficult to deal with. In the other side that was accepted in version 3.4.0 and prior, and this seems to be breaking some rules. 

I'm not sure how to deal with this, but I'm more inclined to keep rejecting those rules. Most rules making use of this "feature" can be rewritten in another way.

**Comment by idiom** [comment] 2016-10-24 10:05
This also affects rules with jumps at the beginning/end of hex strings, not just in alternatives. 

rule hexstring_issue
{
  strings:
    $ok={00 00 00 00 00 00 00 00}
    $fail={[4] 00 00 00 00}
    $fail={00 00 00 00 [4]}
    $ok={00 00 00 00 ?? ?? ?? ??}
  condition:
    $any of them
}

`
error: invalid hex string "$fail": syntax error, unexpected '[', expecting _BYTE_ or _MASKED_BYTE_ or '('
`

Replacing with the equivalent number of wildcards causes the rule to pass. The issue is not seen with versions (<= 3.4).

**Comment by a0rtega** [comment] 2017-02-08 09:22
This also affects to jumps inside groups. Also, making a group optional no longer possible, for example:

Consider the following opcodes:

```
[0x0041eeb0]> pd 20
            ;-- main:
            ;-- main:
            0x0041eeb0      4157           push r15
            0x0041eeb2      4156           push r14
            0x0041eeb4      4155           push r13
            0x0041eeb6      4154           push r12
            0x0041eeb8      55             push rbp
            0x0041eeb9      53             push rbx
            0x0041eeba      4881ec380100.  sub rsp, 0x138
```

Lets say that I want to match the first "push" instructions, but in some binaries, one of them is missing. In yara 3.4.0 I would write a signature like:

```
rule TestRule
{
    strings:
        $string1 = {41 57 41 56 ( [0] | 41 55 ) 41 54}
    condition:
        any of them
}
```

So the opcodes 41 55 (push r13) are optional. The new restriction in yara 3.5.0 makes this string invalid.

**Comment by msm-code** [comment] 2017-02-09 12:51
Additionally things like "short or long push" won't work, and I'm not sure how to fix it:

    $get_subdomain = {8B 0D [4] (5?|68 [4]) E8}

Generally matching code is much harder now, but I guess I'll have to think about changing my rules somehow.

**Comment by plusvic** [comment] 2020-10-06 15:07
Given that this has been the default behavior for a few years and the inconveniences have been minimal, I'm closing this issue.

**Closed by plusvic** 2020-10-06 15:07 UTC
