### ISSUE TITLE
Bug: Calculation of PE overlay is wrong on PEs with multiple sections beginning at the same raw offset

### ISSUE THREAD

**Issue by ladislav-zezula** [VirusTotal/yara#867] opened 2018-05-03 13:19 UTC
The code which checks for position of `pe.overlay` in (file: pe.c, line: 1450) fails in the case when there is more sections having the same raw data offset, but different sizes. This is unusual, but not invalid and Windows loader will load the file just fine.

Sample: `cf62bf1815a93e68e6c5189f689286b66c4088b9507cf3ecf835e4ac3f9ededa`
The sample above has overlay at 0x10400 (66560 decimal), but YARA output is:
```
        overlay
                size = 18744
                offset = 63488
```

**Comment by plusvic** [comment] 2018-05-22 07:53
Duplicate of #864.

**Closed** 2018-05-22 07:53 UTC
Labels: duplicate
