### ISSUE TITLE
Multiple bugs in .NET parsing module

### ISSUE THREAD

**Issue by flandr** [VirusTotal/yara#650] opened 2017-05-05 18:25 UTC
Several parsing bugs exist in the .NET module. Thus far:

1. Malformed stream header records w/o null termination are silently accepted, leading to assumption of name length == 32 and garbage reads of remaining stream header records

2. Tilde (`#~`) parsing assumes that `#Strings` and `#Blob` sections were found, leading to null pointer dereference if this is not the case.

3. Large blob (4-byte blob length encoding) parsing has an off-by-one error on the blob size descriptor, leading to erroneous advancement of the offset for later structures.

This list is probably not comprehensive. In general, sanity checking reserved fields and version numbers as well as computed offsets early could ameliorate some of these problems.

**Comment by wxsBSD** [comment] 2017-05-05 18:27
Can you share samples which trigger these bugs? I'm happy to address them if I can reproduce them.

**Comment by wxsBSD** [comment] 2017-05-05 18:34
Should probably clarify that I can fix the second one without a sample, but having one which triggers it would help.

**Comment by flandr** [comment] 2017-05-05 19:10
Sure, I emailed you a sample that exercises 1 & 2. I'll send a pull request for 3 in a moment.

**Comment by wxsBSD** [comment] 2017-05-06 01:42
I think first one you bring up (stream headers without null termination are silently accepted) is within what I would consider a implementation. The spec says they must be null-terminated and are limited to 32 characters. With no null terminator I have no other option but to take all 32 bytes.

As for issue 2, I'm putting up a pull request right now for those. Thanks again for bringing these to my attention. Very much appreciate them.

**Comment by plusvic** [comment] 2017-05-06 18:46
I guess this issue can be closed as all points have been addressed. Right?

**Comment by wxsBSD** [comment] 2017-05-06 19:06
I believe this can be closed. Thank you for bringing it up!

**Closed** 2017-05-08 07:03 UTC

**Comment by flandr** [comment] 2017-05-08 16:28
Sorry for my delayed response; I was busy this weekend.

> I think first one you bring up (stream headers without null termination are silently accepted) is within what I would consider a correct implementation. The spec says they must be null-terminated and are limited to 32 characters. With no null terminator I have no other option but to take all 32 bytes.

The spec is poorly worded but I disagree:

> Name of the stream as null-terminated variable length array
of ASCII characters, padded to the next 4-byte boundary
with \0 characters. The name is limited to 32 characters.

The primary property of the stream name array is that it is null-terminated; the fact that it is limited to 32 characters is a secondary property. When parsing, the absence of a null character within the 32 byte array should mean that the stream header is malformed.

There are other sanity checks that could be useful when validating these variable-length headers, e.g.
 
 - the parsed stream offsets fall within sane ranges of the file (don't overlap other sections, e.g.)
 - fixed value fields in the streams have expected values (versions in #~, e.g.).

**Comment by wxsBSD** [comment] 2017-05-09 23:43
I've been thinking about your comment regarding stream names, and your argument makes sense. My concern is if we would be failing to parse an otherwise legitimate file if the stream name is not null terminated when the MSFT handler for it would accept it. If MSFT denies this case then I'm fine with implementing your suggestion, otherwise I think we should accept it since it can be parsed properly by MSFT.

Would you happen to be able to create an otherwise legitimate binary with this property and send it to me?

**Comment by flandr** [comment] 2017-05-15 18:10
I prepared a trivial .net console app to test the loader's behavior. The executable and its modified version can be found at https://storage.cloud.google.com/named-lane-4580/blah.zip; the original version prints a message to the console, but the modified version (null terminator and padding bytes replaced with 'a' in stream headers fails to load):

![blah-screenshot](https://cloud.githubusercontent.com/assets/1644146/26072037/02cac7bc-395f-11e7-9918-8e838aebda92.png)

I don't claim that this is a complete test of the behavior of the .net loader, but it suggests that malformed streams headers will be rejected in at least one case.

**Comment by flandr** [comment] 2017-05-15 18:11
Sorry, public link is https://storage.googleapis.com/named-lane-4580/blah.zip

**Comment by wxsBSD** [comment] 2017-05-15 22:30
OK, I'll see if I can get a diff up for this tonight. Thanks for sending it along!
