### ISSUE TITLE
Won't build on MacOS

### ISSUE THREAD

**Issue by bmy** [VirusTotal/yara#665] opened 2017-05-17 18:50 UTC
`MacBook-Pro:yara-3.4.0 $ ./build.sh
./bootstrap.sh: line 2: autoreconf: command not found
./build.sh: line 3: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.`

I get this on both 10.12.5 and vanilla 10.11. Trying to use LOKI with this. Tried the Yara 3.4.0 source  that the LOKI page links, and checked out latest source from this "yara-master" repo. Need is somewhat urgent...serious IOCs. Thanks.

**Comment by wxsBSD** [comment] 2017-05-17 18:53
You don't have the various autotools installed. You will need at least autoconf, automake and libtool.

**Comment by bmy** [comment] 2017-05-17 19:19
ah, ok, thanks very much. should these be flagged as dependencies when installing via homebrew? this is the first time i've installed something from homebrew and not had the requisite ancillary tools also installed. thanks again for your promptness, really appreciated.

**Comment by wxsBSD** [comment] 2017-05-17 19:22
You aren't installing YARA via homebrew, you are building it from source yourself. If you were installing via homebrew and this was happening then the issue is with the homebrew environment. Note, however, that this is not the case here. The documentation you are looking for is here: http://yara.readthedocs.io/en/v3.5.0/gettingstarted.html.

**Comment by bmy** [comment] 2017-05-17 19:23
i should've been clearer – i did both. the homebrew environment doesn't install the three tools you mentioned.

**Comment by wxsBSD** [comment] 2017-05-17 19:25
I'm not intimately familiar with homebrew details but it only lists libtool, autoconf and automake as build dependencies which would make sense as they don't have to be there after the installation of YARA is complete.

**Comment by plusvic** [comment] 2017-10-24 11:48
I'm closing this issue as it seems a bit outdated. If this is a still an issue please re-open it.

**Closed by plusvic** 2017-10-24 11:48 UTC
