### ISSUE TITLE
assert failure

### ISSUE THREAD

**Issue by mccoysc** [VirusTotal/yara#514] opened 2016-09-07 06:10 UTC
assert failure at line 467 in file exec.c of yara version 3.5 when rule is:
rule fire2013 : webshell
{
    meta:
        author      = "Vlad https://github.com/vlad-s"
        date        = "2016/07/18"
        description = "Catches a webshell"
    strings:
        $a = "eval(\"\x65\x76\x61\x6C\x28\x67\x7A\x69\x6E\x66\x6C\x61"
        $b = "yc0CJYb+O//Xgj9/y+U/dd//vkf'\x29\x29\x29\x3B\")"
    condition:
        all of them
}

and the file content to scan is :
eval(\"\x65\x76\x61\x6C\x28\x67\x7A\x69\x6E\x66\x6C\x61

the code which bug occoured like this 

457      case OP_OBJ_LOAD:
458        identifier = _(char__)(ip + 1);
459        ip += sizeof(uint64_t);
460
461        r1.o = (YR_OBJECT_) yr_hash_table_lookup(
462            context->objects_table,
463            identifier,
464           NULL);
465
467        assert(r1.o != NULL);
468        push(r1);
469        break;

**Comment by plusvic** [comment] 2016-09-07 07:32
I'm unable to reproduce this issue. With that rule YARA 3.5 is working fine for me. Are you able to reproduce it with this single rule? Or are you running YARA with more rules besides this one?

**Comment by mccoysc** [comment] 2016-09-07 07:44
https://github.com/Yara-Rules/rules



364589886@qq.com
 
From: Victor M. Alvarez
Date: 2016-09-07 15:32
To: VirusTotal/yara
CC: mccoysc; Author
Subject: Re: [VirusTotal/yara] assert failure (#514)
I'm unable to reproduce this issue. With that rule YARA 3.5 is working fine for me. Are you able to reproduce it with this single rule? Or are you running YARA with more rules besides this one?

**Comment by mccoysc** [comment] 2016-09-07 07:46
https://github.com/Yara-Rules/rules 

all rules dwonload from this URL.



364589886@qq.com
 
From: Victor M. Alvarez
Date: 2016-09-07 15:32
To: VirusTotal/yara
CC: mccoysc; Author
Subject: Re: [VirusTotal/yara] assert failure (#514)
I'm unable to reproduce this issue. With that rule YARA 3.5 is working fine for me. Are you able to reproduce it with this single rule? Or are you running YARA with more rules besides this one?

**Comment by plusvic** [comment] 2016-09-07 08:08
Still unable to reproduce it. A stack trace would be great.

**Comment by mccoysc** [comment] 2016-09-07 08:12
would you give me your email address that can receive big attachment files so that i will send my all project files to you



364589886@qq.com
 
From: Victor M. Alvarez
Date: 2016-09-07 16:08
To: VirusTotal/yara
CC: mccoysc; Author
Subject: Re: [VirusTotal/yara] assert failure (#514)
Still unable to reproduce it. A stack trace would be great.

**Comment by plusvic** [comment] 2016-09-07 08:22
plusvic at gmail

**Comment by kallanreed** [comment] 2016-09-16 18:31
I'm seeing this as well on Windows when trying to use modules (hash specifically) in 3.5.0.
`import "hash" rule test_hash { condition: filesize < 500KB and hash.md5(0, filesize) == "f4f684066175b77e0c3a000549d2922c" }`

I'll try to dig in a little more, but here's a stack trace:
```
>	ucrtbased.dll!issue_debug_notification(const wchar_t * const message) Line 125	C++
 	ucrtbased.dll!__acrt_report_runtime_error(const wchar_t * message) Line 142	C++
 	ucrtbased.dll!abort() Line 61	C++
 	ucrtbased.dll!common_assert_to_stderr_direct(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) Line 124	C++
 	ucrtbased.dll!common_assert_to_stderr<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) Line 142	C++
 	ucrtbased.dll!common_assert<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number, void * const return_address) Line 383	C++
 	ucrtbased.dll!_wassert(const wchar_t * expression, const wchar_t * file_name, unsigned int line_number) Line 405	C++
 	YaraNugetTest.exe!yr_execute_code(_YR_RULES * rules, _YR_SCAN_CONTEXT * context, int timeout, __int64 start_time) Line 468	C++
 	YaraNugetTest.exe!yr_rules_scan_mem_blocks(_YR_RULES * rules, _YR_MEMORY_BLOCK_ITERATOR * iterator, int flags, int(*)(int, void *, void *) callback, void * user_data, int timeout) Line 470	C++
 	YaraNugetTest.exe!yr_rules_scan_file(_YR_RULES * rules, const char * filename, int flags, int(*)(int, void *, void *) callback, void * user_data, int timeout) Line 615	C++
 	YaraNugetTest.exe!main() Line 73	C++
 	[External Code]	
```

**Comment by kallanreed** [comment] 2016-09-21 00:00
Part of the issue for me is that after 073c7b287f1c0e72d24b602ebdf91a2ae9cd3672d the bits from the 2015 project no longer imports modules properly.

**Comment by kallanreed** [comment] 2016-09-23 14:57
@Mccoysc this should be fixed in Master. Can you try rebuilding?

**Comment by plusvic** [comment] 2017-06-06 15:05
Closing because of this issue is out of date. Please reopen if still valid.

**Closed by plusvic** 2017-06-06 15:05 UTC
