### ISSUE TITLE
modules/pe.c:1213:44: error: dereferencing pointer to incomplete type

### ISSUE THREAD

**Issue by kloisle** [VirusTotal/yara#423] opened 2016-03-14 15:45 UTC
During make I get this error:

modules/pe.c: In function 'pe_parse_certificates':
modules/pe.c:1213:44: error: dereferencing pointer to incomplete type
       sig_alg = OBJ_nid2ln(OBJ_obj2nid(cert->sig_alg->algorithm));

Any idea what could be causing this? Thanks in advance.

**Comment by wxsBSD** [comment] 2016-03-14 15:47
What platform are you building on? Exactly how, and what, did you build? Are you building latest master, and with what configure and make args?

**Comment by kloisle** [comment] 2016-03-14 15:57
I am building on rhel 7.1.

built openssl before doing this.

Redownloaded the master.zip a short while ago.

ran ./bootstrap.sh
then ran ./configure
then ran make

error message appears.

**Comment by wxsBSD** [comment] 2016-03-14 17:04
How did you build openssl? I built it fine after installing openssl-devel.

**Comment by kloisle** [comment] 2016-03-14 19:38
I had not installed openssl-dev. I built openssl from source.

Do you have any idea how I can resolve the issue? Yum Installed openssl-dev and ran through bootstrap and configure again but unfortunately that did not resolve.

Kanhai Lisle
Lead Linux Engineer
Ctrl-IT Inc.
13 West Kings House Rd.
Unit 20
Kingston, JA
www.ctrl-it.com.jm
Office: 876.631.7554
Cell: 876.997.3716
CTRL-IT logo_Coloured
________________________________
From: Wesley Shields
Sent: Monday, March 14, 2016 1:06 PM
To: plusvic/yara
CC: "Kanhai G. Lisle"
Subject: Re: [yara] modules/pe.c:1213:44: error: dereferencing pointer to incomplete type (#423)



How did you build openssl? I built it fine after installing openssl-devel.

-
Reply to this email directly or view it on GitHub<https://github.com/plusvic/yara/issues/423#issuecomment-196413237>.

This message is confidential. It may also be privileged or otherwise protected by work product immunity or other legal rules. If you have received it by mistake, please let us know by e-mail reply and delete it from your system; you may not copy this message or disclose its contents to anyone. Please send us by fax any message containing deadlines as incoming e-mails are not screened for response deadlines. The integrity and security of this message cannot be guaranteed on the Internet.

**Comment by wxsBSD** [comment] 2016-03-14 19:54
It is probably picking up whatever version of OpenSSL you installed manually, which may have a problem in it. Which version of OpenSSL did you build and install manually? I'll try and replicate as we will eventually have to fix this if it is indeed a problem.

You will want to remove anything you installed manually and then rebuild yara.

**Comment by plusvic** [comment] 2016-03-23 18:34
Someone else is experiencing the same problem: https://groups.google.com/forum/#!topic/yara-project/XL91dNpQFd0

**Comment by wxsBSD** [comment] 2016-03-30 18:29
I'm able to reproduce this if I build with the latest OpenSSL master (not sure if the changes ever made it in a release). The hint came from the fact that the post you mention above includes openssl-29fa0a1 in it, which made me test with the latest master.

Looks like some of the internal structures I was using are being made opaque (https://github.com/openssl/openssl/commit/a6eb1ce6a989d01bb00e9749789b690744be506c). I should be able to use the new X509_SIG_get0 and #ifdef around this.

**Comment by plusvic** [comment] 2018-05-31 08:21
Fixed in 38566c0a9f8bd1cd5f609482342ffa07aba6d23a

**Closed by plusvic** 2018-05-31 08:21 UTC
