### ISSUE TITLE
yara rule multiple condition

### ISSUE THREAD

**Issue by H1-N1** [VirusTotal/yara#845] opened 2018-03-20 15:08 UTC
hello!
i'm facing a prob in writing multiple condition check
in this exemple i'm checking some string in plain text file to black list it
but if i add the last conditions it spoil all scan
files :
                           BITCOIN PRIVATE KEYS
    
How to get:  
Step 1 - Send 0.0005 BTC to this bitcoin address: 1ionChGCZkjP4xSSYqn6HcQEkHBpJtv6W
Step 2 - Email to this address alt.qt-btc@yopmail.com.
Step 3 - Receive the private keys
19KJZ5aqWnrrCaNAS5Pbd4uknPFBxjALRt
1Jz6HEKNJpYjXAYRLn49QUUUrizL5qGxjM
18vo26nEeDt1Tw17CuWap3F5rKJjBXSMmL`

rule :
rule blacklist
{
strings:
$data_format = "#EXTINF" nocase
$data_format1 = /\b[\w.-]+@[\w.-]+.\w+\b/
//$data_format2 = /^([\w.~!@#$%&*_-]{0,30})[: |-]+([\w\.\~!@#$%&*_-^*]{4,32})([ ]+)?/
$keyword1 = "--app-name=LeagueClient" nocase // League of Legends Debug Log
$keyword2 = "common.application_name: LeagueClient" // League of Legends Debug Log
$keyword3 = "Minecraft Version:"
$keyword4 = "---- Minecraft Crash Report ----"
$keyword5 = "Server version"
$keyword6 = "server configuration"
$keyword7 = /([\w\d$-><()[]{}][ \t]?)([\w\d$-><()[]{}])[ \t]?=[ \t]?([.\w\d$-><()"'[]{},]+)[;]?[ ][\n\r]?/
$keyword8 = "minecraft.jar"
$keyword9 = /(<.+?>)/
condition:
(any of ($keyword) and not any of ($data_format*)) or (not any of ($data_format*)) or #data_format < 10

}

this is resulte of the scan

0x146:$data_format1: alt.qt-btc@yopmail.com
0x149:$data_format1: .qt-btc@yopmail.com
0x14a:$data_format1: qt-btc@yopmail.com
0x14c:$data_format1: -btc@yopmail.com
0x14d:$data_format1: btc@yopmail.com
0x0:$data_format2: https://pastebin.com/PLpKtX9V
0xf7:$data_format2: address: 1ionChGCZkjP4xSSYqn6HcQEkHBpJtv6W�

**Comment by plusvic** [comment] 2018-05-14 08:43
Duplicate of#844.

**Closed by plusvic** 2018-05-14 08:43 UTC
Labels: duplicate
