### ISSUE TITLE
Comment throws an error

### ISSUE THREAD

**Issue by geekscrapy** [VirusTotal/yara#1839] opened 2022-12-16 15:28 UTC
**Describe the bug**
It seems like the rule parser doesn't honor a comment properly

**To Reproduce**
When running yara with the below command and the rule file `err.yara` I get a syntax. But if I remove the comments (as in `no-err.yara`) I dont get the error:

`$ yara err.yara /dev/random`

`err.yara`
```yara
import "math"
import "console"

rule err {
    //     $ = { ?? }
    condition:
        console.log(math.entropy(0,filesize))
}
```

Error: `error: rule "err" in err.yara(5): syntax error`

`no-err.yara`
```yara
import "math"
import "console"

rule err {
    condition:
        console.log(math.entropy(0,filesize))
}
```

**Expected behavior**
For yara to ignore the commented line

**Please complete the following information:**
```bash
$ uname -a
Darwin 21.6.0 Darwin Kernel Version 21.6.0; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64 i386 Darwin
$
$ yara -v
4.2.3
```

**Comment by plusvic** [comment] 2022-12-19 10:29
Duplicate of #1819

**Closed by plusvic** 2022-12-19 10:29 UTC
Labels: bug
