### ISSUE TITLE
Clamav to Yara rules - internal fatal errors and warnings

### ISSUE THREAD

**Issue by 1982Dmitry** [VirusTotal/yara#509] opened 2016-08-26 06:21 UTC
`yara -v` yara 3.5.0

OS: Arch Linux
Kernel: Linux4.7.2

`sigtool -u main.cvd` # works fine
`python2 clamav_to_yara.py -f main.ndb -o y.yar` # works fine
I'm using this code: [clamav_to_yara.py](https://raw.githubusercontent.com/mattulm/volgui/master/tools/clamav_to_yara.py)
`less y.yar` # looks like normal yara rules
But when I scan something: `yara y.yar mal`
I'm getting this:

> y.yar(354879): warning: $a36 is slowing down scanning
y.yar(354883): warning: $a40 is slowing down scanning
y.yar(354899): warning: $a56 is slowing down scanning
y.yar(354902): warning: $a59 is slowing down scanning
y.yar(354903): warning: $a60 is slowing down scanning
y.yar(354904): warning: $a61 is slowing down scanning
y.yar(354915): warning: $a72 is slowing down scanning
y.yar(354917): warning: $a74 is slowing down scanning
y.yar(354930): warning: $a87 is slowing down scanning
y.yar(354939): warning: $a96 is slowing down scanning
y.yar(370998): error: internal fatal error
y.yar(398324): warning: $a1 is slowing down scanning (critical!)
y.yar(402191): warning: $a0 is slowing down scanning
y.yar(402201): warning: $a0 is slowing down scanning
y.yar(407146): warning: $a0 is slowing down scanning

What causes internal fatal errors or even this warns?

**Comment by wxsBSD** [comment] 2016-08-26 06:27
The warnings are because you are producing strings which cause YARA to slow down. The exact cause is hard to know without an exact reproducible case. The same goes for the error. Can you please share the exact set of inputs here?

**Comment by 1982Dmitry** [comment] 2016-08-26 07:12
Do you  mean converted Yara rules?

**Comment by wxsBSD** [comment] 2016-08-26 07:30
Yes, that would be fine.

**Comment by 1982Dmitry** [comment] 2016-08-26 07:36
It's very big ~30 MB, mega link: https://mega.nz/#!sUB3hAoJ!vT3zGQ17U3MyiM-sNhH19XNINi75wkvrr2EKsX3RcIQ
Yara and yara-python work fine with small amount of rules, if I combine like this one, I'll get errors.

**Comment by 1982Dmitry** [comment] 2016-08-26 07:42
Aaha, I think I made mistake, one rule file must contain only one rule. 
Oh, sorry. my mistake.

**Comment by plusvic** [comment] 2016-08-26 08:49
The internal fatal errors are caused by strings like this one:

$a0 = { 4a4249472333324465636f6465[0-100]73747265616d0a????????(40|41|42|43|44|45|46|47|48|49|4a|4b|4c|4d|4e|4f)(31|30|29|28|27|26|25|24|23|22|21|20|19|18|17|16|15|14|13|12|11|10|09|08|07|06|05|04|03|02|01|00)(8a|8b|8c|8d|8e|8f|90|91|92|93|94|95|96|97|98|99|9a|9b|9c|9d|9e|9f|a0|a1|a2|a3|a4|a5|a6|a7|a8|a9|aa|ab|ac|ad|ae|af|b0|b1|b2|b3|b4|b5|b6|b7|b8|b9|ba|bb|bc|bd|be|bf|c0|c1|c2|c3|c4|c5|c6|c7|c8|c9|ca|cb|cc|cd|ce|cf|d0|d1|d2|d3|d4|d5|d6|d7|d8|d9|da|db|dc|dd|de|df|e0|e1|e2|e3|e4|e5|e6|e7|e8|e9|ea|eb|ec|ed|ee|ef|f0|f1|f2|f3|f4|f5|f6|f7|f8|f9|fa|fb|fc|fd|fe|ff) }

Those strings contain too many alternative (|) operators. Increasing RE_MAX_SPLIT_ID in re.c:58 mitigates the problem. With RE_MAX_SPLIT_ID = 255 only two rules fail with that error.

I'm going to close this issue because this is the expected behavior.

**Closed by plusvic** 2016-08-26 08:49 UTC
