### ISSUE TITLE
access violation in dotnet module

### ISSUE THREAD

**Issue by CaldurG** [VirusTotal/yara#967] opened 2018-10-22 08:06 UTC
access violation occurs while scanning file https://github.com/CaldurG/yara/blob/yplsml/tests/dotnet.av It is in dotnet_parse_tilde_2 function when accessing memberref_row.

Rules:
```
import "dotnet"

rule test {
  strings:
    $ = "test"
  condition:
    all of them
}
```

**Comment by plusvic** [comment] 2018-10-23 13:10
Duplicate of #970

**Closed by plusvic** 2018-10-23 13:10 UTC
Labels: duplicate
